[pytest]
# -ra: muestra un resumen extra al final (excepto passed)
# -vv: muestra toda la info de los asserts (importante para leer tus mensajes largos)
# --tb=short: Solo muestra la línea del fallo y el mensaje, no todo el código fuente.
addopts = -ra -vv --tb=short