@startuml
skinparam linetype ortho
hide empty members
hide empty description

package "Entradas" {
  component [Vectores de tensión y periodo de muestreo] as EntradaDatos
}

package "Motor de Cálculo" {

  package "Fase I" {
    component [Eliminar offset] as ModOffset
    component [Normalizar polaridad] as ModPolaridad
    component [Escalar a valor unitario] as ModNormUnit
  }

  package "Fase II" {
    component [Alinear tiempo] as ModAlineacion
    component [Clasificar impulso] as ModClasificador
    component [Ajuste de curva] as ModAjusteDobleExp
    component [Escalar por relación de amplitud] as ModEscalamientoLIC
    component [Detectar instante de corte] as ModCorteLIC
  }

  package "Fase III" {
    component [Obtener curva residual] as ModResidual
    component [Filtrar] as ModFiltroIIR
    component [Sintetizar curva de ensayo] as ModCurvaEnsayo
    component [Calcular Parámetros] as ModParametros
  }
}

package "Salidas" {
  component [Parámetros Característicos (Ut, T1, T2, OS%)] as SalidaResultados
}

EntradaDatos --> ModOffset
ModOffset --> ModPolaridad
ModPolaridad --> ModNormUnit
ModNormUnit --> ModAlineacion
ModAlineacion --> ModClasificador
ModNormUnit --> ModAjusteDobleExp
ModClasificador --> ModAjusteDobleExp
ModClasificador --> ModEscalamientoLIC
ModEscalamientoLIC --> ModCorteLIC
ModCorteLIC --> ModResidual
ModAjusteDobleExp --> ModResidual
ModResidual --> ModFiltroIIR
ModFiltroIIR --> ModCurvaEnsayo
ModCurvaEnsayo --> ModParametros
ModParametros --> SalidaResultados

@enduml
