@startuml
skinparam linetype ortho
hide empty members
hide empty description

package "Abstracción de hardware" {
  package "Gestión de recursos" {
    component [Administrador de recursos VISA] as VisaManager
    component [Escáner de dispositivos] as Escaner
    component [Manejador de excepciones] as GestorExcepciones
  }

  package "Protocolo SCPI" {
    component [Configurar parámetros] as Setters
    component [Consultar estado] as Getters
    component [Formatear mensajes] as FormateadorSCPI
  }

  package "Adquisición y desempaquetado" {
    component [Verificador de estado de disparo] as Polling
    component [Desempaquetador de datos] as Desempaquetador
  }
}

package "Control del S.O." {
  component [Controlador de puerto] as DriverCDC
}

package "Osciloscopio" {
  component [Puerto USB] as PuertoUSB
  component [Procesador de comandos SCPI] as ProcesadorSCPI
  component [Convertidor ADC y Memoria interna] as MemoriaADC
}

VisaManager --> Escaner
Escaner --> DriverCDC
GestorExcepciones ..> VisaManager

Setters --> FormateadorSCPI
Getters --> FormateadorSCPI
FormateadorSCPI --> DriverCDC

Polling --> Getters
Desempaquetador <-- DriverCDC

DriverCDC <--> PuertoUSB
PuertoUSB <--> ProcesadorSCPI
ProcesadorSCPI <--> MemoriaADC

@enduml
