@startuml
skinparam responseMessageBelowArrow true

actor "Operador" as user
participant "Interfaz gráfica" as gui
participant "Presentador" as pres
participant "Controlador de hardware" as hal
participant "Motor de cálculo" as dsp
participant "Osciloscopio" as dso
participant "Generador de impulsos" as marx

user -> gui: Iniciar captura
activate gui
gui -> pres: Notificar \niniciar \ncaptura
activate pres
pres -> hal: Configurar \ndisparo
activate hal
hal -> dso: Comando SCPI
activate dso
dso --> hal: Confirmación de \nconfiguración
deactivate dso
hal --> pres: Disparo listo
deactivate hal
pres -> pres: Iniciar hilo \nsecundario asíncrono

loop Sondeo de estado de disparo en segundo plano
    pres -> hal: Consultar estado \nde captura
    activate hal
    hal -> dso: Consulta SCPI
    activate dso
    dso --> hal: Estado "No disparado"
    deactivate dso
    hal --> pres: Captura en espera
    deactivate hal
end

marx -> dso: Evento físico: \nDescarga de alta tensión
activate dso
note over dso
  Estado cambia a "Disparado".
end note

pres -> hal: Consultar estado \nde captura
activate hal
hal -> dso: Consulta SCPI
dso --> hal: Estado "Disparado"
deactivate dso
hal --> pres: Notificar \ncaptura \ndetectada
deactivate hal

pres -> pres: Finalizar hilo \nasíncrono

pres -> hal: Solicitar descarga \nde datos brutos
activate hal
hal -> dso: Solicitud de \nbloque de memoria
activate dso
dso --> hal: Bloque de datos
deactivate dso

hal -> hal: Desempaquetar datos brutos
hal --> pres: Vector de tensión \nsin escalar y dt
deactivate hal

pres -> pres: Reescalar vector \ncon atenuación física

pres -> dsp: Transferir vectores y solicitar cálculo normativo
activate dsp

dsp -> dsp: Calcular parámetros \n(Ut, T1, T2/Tc, OS%)
dsp --> pres: Retornar curva de ensayo y resultados
deactivate dsp

pres -> gui: Inyectar onda \ny parámetros \ncalculados
deactivate pres

gui -> user: Renderizar curvas \ny actualizar \nindicadores \nen pantalla
deactivate gui

@enduml