@startuml
skinparam monochrome true
skinparam linetype ortho
skinparam componentStyle uml2

package "GUI (Vista - PySide6)" {
    [MainWindow] <<View>>
    [Ui_MainWindow] <<Qt Designer>>
    [MainWindow] -up-|> [Ui_MainWindow]
}

package "Orquestación (Presentador)" {
    [MainPresenter] <<Presentador>>
    [WaitWaveformThread] <<QThread>>
    [MainPresenter] *-- [WaitWaveformThread] : Lanza \nsub-hilo
}

package "Modelo (Backend Físico y Lógico)" {
    [GWInstekGDS1000AU] <<HAL - PyVISA>>
    [LightningImpulseAnalyzer] <<Motor matemático>>
    [FileManager] <<IO - HDF5/CSV>>
}

' Relaciones de acoplamiento MVP
[MainWindow] <---> [MainPresenter] : Signals / Slots\n (Eventos y UI)

' Relaciones Presentador -> Modelo
[WaitWaveformThread] ---> [GWInstekGDS1000AU] : Polling \nde Trigger
[MainPresenter] --> [GWInstekGDS1000AU] : Comandos\nSCPI
[MainPresenter] --> [LightningImpulseAnalyzer] : Vectores\nde onda
[MainPresenter] --> [FileManager] : Estructuras\nHDF5 / CSV
@enduml