@startuml
skinparam linetype ortho
hide empty members
hide empty description

package "Vista" {
  component [Interfaz de usuario] as GUI
}

package "Coordinación" {
  component [Presentador] as Presentador
}

package "Modelo: Persistencia" {
  component [Validador de entrada y estado] as Validador
  component [Administrador base de datos] as AdminHDF5
  component [Generador de respaldos] as RespaldosCSV
  component [Exportador a planillas] as Exportador
}

package "Sistema de archivos en disco" {
  component [Base de datos] as ArchivoHDF5
  component [Archivos de respaldo] as ArchivosCSV
  component [Planilla exportada] as HojaCalculo
}

GUI --> Presentador

Presentador --> Validador
Validador ..> Presentador

Presentador --> AdminHDF5
AdminHDF5 --> ArchivoHDF5
AdminHDF5 --> RespaldosCSV
RespaldosCSV --> ArchivosCSV

Presentador --> AdminHDF5
ArchivoHDF5 ..> AdminHDF5
AdminHDF5 ..> Presentador

Presentador --> Exportador
Exportador --> HojaCalculo

Presentador --> GUI

@enduml
