@startuml

skinparam responseMessageBelowArrow true

actor "Operador" as Operador
participant "Interfaz gráfica" as Vista
participant "Presentador" as Presentador
participant "Gestor de archivos" as GestorArchivos
database "Base de datos" as HDF5
participant "Resguardo" as CSV

Operador -> Vista : Solicitar guardar \nde ensayo
activate Vista

Vista -> Presentador : Solicitar \npersistencia
activate Presentador

Presentador -> Presentador : Validar datos \nde onda

Presentador -> GestorArchivos : Organizar \nalmacenamiento \nde ensayo
activate GestorArchivos

GestorArchivos -> HDF5 : Escribir \nestructura \nde datos
activate HDF5
HDF5 --> GestorArchivos : Confirmar \npersistencia
deactivate HDF5

GestorArchivos -> CSV : Generar tabla de respaldo
activate CSV
CSV --> GestorArchivos : Confirmar creación \nde archivo .csv
deactivate CSV

GestorArchivos --> Presentador : Notificar \nalmacenamiento \nexitoso
deactivate GestorArchivos

Presentador -> Vista : Notificar \nguardado \nfinalizado
deactivate Presentador

Vista --> Operador : Mostrar mensaje \nde confirmación \nde guardado en \npantalla
deactivate Vista

@enduml
