@startuml
skinparam linetype ortho

actor "Operador" as Operador
participant "Interfaz\ngráfica" as Vista
participant "Presentador" as Presentador
participant "Controlador\n de hardware" as HAL
participant "Hilo de monitoreo" as Hilo
entity "Osciloscopio" as Osciloscopio
participant "Motor de cálculo" as MotorCalculo
participant "Gestor de archivos" as FileManager

Operador -> Vista : Configurar \nparámetros\n y solicitar \ncaptura
activate Vista

Vista -> Presentador : Notificar inicio\n de captura
activate Presentador

Presentador -> HAL : Configurar\n instrumento
activate HAL
HAL -> Osciloscopio : Enviar comandos SCPI
HAL --> Presentador : Confirmar \nestado del \ninstrumento
deactivate HAL

Presentador -> Hilo : Iniciar \nmonitoreo\n de disparo
activate Hilo

Hilo -> Osciloscopio : Consultar \nestado de\n adquisición
activate Osciloscopio

... Ocurrencia del ensayo de impulso en Alta Tensión ...

Osciloscopio -> Osciloscopio : Capturar y \nalmacenar \nonda
Osciloscopio --> Hilo : Notificar \ndetección \nde onda y \nfin de captura
deactivate Osciloscopio

Hilo --> Presentador : Emitir señal de \ncaptura completada
deactivate Hilo

Presentador -> HAL : Solicitar descarga \nde datos brutos
activate HAL
HAL -> Osciloscopio : Transferir memoria
Osciloscopio --> HAL : Bloque de datos
HAL --> Presentador : Entregar vectores \nde tiempo y tensión \ndecodificados
deactivate HAL

Presentador -> MotorCalculo : Ejecutar análisis de onda.
activate MotorCalculo
MotorCalculo --> Presentador : Retornar curva de ensayo y parámetros calculados (Ut, T1, T2, OS)
deactivate MotorCalculo

Presentador -> Vista : Actualizar \ngráfica y\n mostrar \nparámetros
Vista --> Operador : Presentar \nresultado\n en pantalla
deactivate Vista

Presentador -> FileManager : Registrar captura y guardar en base de datos
activate FileManager
FileManager --> Presentador : Confirmar persistencia de datos
deactivate FileManager

deactivate Presentador

@enduml
